language: node_js
node_js:
  - "node"
notifications:
  email: false
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - npm run build
  - cypress install
before_script:
  - npm start -- --silent &
script: 
  - $(npm bin)/cypress run --record